; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32@6.9.0
framework = arduino
monitor_speed = 115200
lib_extra_dirs=C:\Users\Adam\Documents\PlatformIO\Rakieta\Libs
lib_deps =
    bblanchon/ArduinoJson@^7.0.3
    adafruit/Adafruit NeoPixel@^1.12.3
    evert-arias/EasyButton @ ^2.0.3

[env:esp32dev]
board = esp32dev
build_flags = -I include -D ESP_WROOM_32D

[env:esp32-c3]
board = lolin_c3_mini
build_flags = -I include -D ESP_C3_MINI